extra-deps:
- attoparsec-iso8601-1.0.0.0
- http-api-data-0.3.7
- natural-transformation-0.4

resolver: lts-7.9
flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/Palmik/bson-generic.git
    commit: e078def65d0dee1ea7e3205f445e47d5937851f3

extra-include-chats: []
